---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Configure http reverse proxy
  when: reverse_proxy is defined and reverse_proxy | length > 0
  block:
    - name: Deploy Nginx subdomain proxy configuration
      ansible.builtin.template:
        src: "{{ role_path }}/templates/nginx.conf.j2" 
        dest: "/etc/nginx/sites-available/{{ item.subdomain }}.{{ top_level_domain }}.conf"
      notify: Reload nginx
      loop: "{{ reverse_proxy }}" 

    - name: Enable Nginx subdomain proxy
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ item.subdomain }}.{{ top_level_domain }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ item.subdomain }}.{{ top_level_domain }}.conf"
        state: link
      notify: Reload nginx
      loop: "{{ reverse_proxy }}" 

- name: Configure https reverse proxy
  when: reverse_proxy_ssl is defined and reverse_proxy_ssl | length > 0
  block:
    - name: copy certificate onto server
      ansible.builtin.copy:
        src: "{{ ssl_certificate.src }}/{{ ssl_certificate.name }}" 
        dest: "{{ ssl_certificate.dest }}" 
        mode: 0644
        owner: root
        group: root

    - name: copy key onto server
      ansible.builtin.copy:
        src: "{{ ssl_key.src }}/{{ ssl_key.name }}" 
        dest: "{{ ssl_key.dest }}" 
        mode: 0600
        owner: root
        group: root

    - name: Deploy Nginx subdomain proxy configuration
      ansible.builtin.template:
        src: "{{ role_path }}/templates/nginx.conf.ssl.j2" 
        dest: "/etc/nginx/sites-available/{{ item.subdomain }}.{{ top_level_domain }}.conf"
      notify: Reload nginx
      loop: "{{ reverse_proxy_ssl }}" 

    - name: Enable Nginx subdomain proxy
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ item.subdomain }}.{{ top_level_domain }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ item.subdomain }}.{{ top_level_domain }}.conf"
        state: link
      notify: Reload nginx
      loop: "{{ reverse_proxy_ssl }}" 

